
repo:
https://github.com/Gogh-Co/Gogh

demo:
https://gogh-co.github.io/Gogh/

pacman -Syu dconf
export TERMINAL=gnome-terminal
# export TERMINAL=iterm2

git clone https://github.com/Gogh-Co/Gogh.git
cd Gogh/installs

# aci is what i'm using atm

./3024-day.sh
./dehydration.sh
./hybrid.sh
./nighty.sh
./solarized-light.sh
./3024-night.sh
./desert.sh
./ibm-3270-high-contrast.sh
./nord-light.sh
./sonokai.sh
./aci.sh
./dimmed-monokai.sh
./ibm3270.sh
./nord.sh
./spacedust.sh
./aco.sh
./dissonance.sh
./ic-green-ppl.sh
./novel.sh
./spacegray-eighties-dull.sh
./adventure-time.sh
./dracula.sh
./ic-orange-ppl.sh
./obsidian.sh
./spacegray-eighties.sh
./afterglow.sh
./earthsong.sh
./idle-toes.sh
./ocean-dark.sh
./spacegray.sh
./alien-blood.sh
./elemental.sh
./ir-black.sh
./oceanic-next.sh
./spring.sh
./apprentice.sh
./elementary.sh
./jackie-brown.sh
./ollie.sh
./square.sh
./argonaut.sh
./elic.sh
./japanesque.sh
./omni.sh
./srcery.sh
./arthur.sh
./elio.sh
./jellybeans.sh
./one-dark.sh
./summer-pop.sh
./atom.sh
./espresso-libre.sh
./jup.sh
./one-half-black.sh
./sundried.sh
./aura.sh
./espresso.sh
./kanagawa.sh
./one-light.sh
./sweet-eliverlara.sh
./ayu-dark.sh
./everblush.sh
./kibble.sh
./oxocarbon-dark.sh
./sweet-terminal.sh
./ayu-light.sh
./everforest-dark.sh
./kokuban.sh
./palenight.sh
./symphonic.sh
./ayu-mirage.sh
./everforest-light.sh
./laserwave.sh
./pali.sh
./synthwave-alpha.sh
./azu.sh
./fairy-floss-dark.sh
./later-this-evening.sh
./panda.sh
./synthwave.sh
./belafonte-day.sh
./fairy-floss.sh
./lavandula.sh
./papercolor-dark.sh
./teerb.sh
./belafonte-night.sh
./fishtank.sh
./liquid-carbon.sh
./papercolor-light.sh
./tender.sh
./bim.sh
./flatland.sh
./liquid-carbon-transparent.sh
./paraiso-dark.sh
./terminal-basic.sh
./birds-of-paradise.sh
./flat-remix.sh
./lunaria-dark.sh
./paul-millr.sh
./terminix-dark.sh
./blazer.sh
./flat.sh
./lunaria-eclipse.sh
./pencil-dark.sh
./thayer-bright.sh
./bluloco-light.sh
./foxnightly.sh
./lunaria-light.sh
./pencil-light.sh
./tin.sh
./bluloco-zsh-light.sh
./freya.sh
./maia.sh
./peppermint.sh
./tokyo-night-light.sh
./borland.sh
./frontend-delight.sh
./man-page.sh
./pixiefloss.sh
./tokyo-night.sh
./breath-darker.sh
./frontend-fun-forrest.sh
./mar.sh
./pnevma.sh
./tokyo-night-storm.sh
./breath-light.sh
./frontend-galaxy.sh
./material.sh
./powershell.sh
./tomorrow-night-blue.sh
./breath.sh
./geohot.sh
./mathias.sh
./predawn.sh
./tomorrow-night-bright.sh
./breath-silverfox.sh
./github.sh
./medallion.sh
./pro.sh
./tomorrow-night-eighties.sh
./breeze.sh
./gogh.sh
./misterioso.sh
./purple-people-eater.sh
./tomorrow-night.sh
./broadcast.sh
./gooey.sh
./molokai.sh
./red-alert.sh
./tomorrow.sh
./brogrammer.sh
./google-dark.sh
./mona-lisa.sh
./red-sands.sh
./toy-chest.sh
./c64.sh
./google-light.sh
./mono-amber.sh
./relaxed.sh
./treehouse.sh
./cai.sh
./gotham.sh
./mono-cyan.sh
./rippedcasts.sh
./twilight.sh
./campbell.sh
./grape.sh
./mono-green.sh
./rose-pine-dawn.sh
./ura.sh
./catppuccin-frappe.sh
./grass.sh
./monokai-dark.sh
./rose-pine-moon.sh
./urple.sh
./catppuccin-latte.sh
./gruvbox-dark.sh
./monokai-pro-ristretto.sh
./rose-pine.sh
./vag.sh
./catppuccin-macchiato.sh
./gruvbox-material.sh
./monokai-pro.sh
./royal.sh
./vaughn.sh
./catppuccin-mocha.sh
./gruvbox.sh
./monokai-soda.sh
./sat.sh
./vibrant-ink.sh
./chalkboard.sh
./hardcore.sh
./mono-red.sh
./seafoam-pastel.sh
./vs-code-dark.sh
./chalk.sh
./harper.sh
./mono-white.sh
./sea-shells.sh
./vs-code-light.sh
./chameleon.sh
./hemisu-dark.sh
./mono-yellow.sh
./seti.sh
./warm-neon.sh
./ciapre.sh
./hemisu-light.sh
./morada.sh
./shaman.sh
./wez.sh
./clone-of-ubuntu.sh
./highway.sh
./n0tch2k.sh
./shel.sh
./wild-cherry.sh
./clrs.sh
./hipster-green.sh
./neon-night.sh
./slate.sh
./wombat.sh
./cobalt-2.sh
./homebrew-light.sh
./neopolitan.sh
./smyck.sh
./wryan.sh
./cobalt-neon.sh
./homebrew-ocean.sh
./nep.sh
./snazzy.sh
./wzoreck.sh
./colorcli.sh
./homebrew.sh
./neutron.sh
./soft-server.sh
./zenburn.sh
./crayon-pony-fish.sh
./horizon-bright.sh
./nightlion-v1.sh
./solarized-darcula.sh
./dark-pastel.sh
./horizon-dark.sh
./nightlion-v2.sh
./solarized-dark-higher-contrast.sh
./darkside.sh
./hurtado.sh
./night-owl.sh
./solarized-dark.sh