- name: make sure bash is installed
  package:
    name:
      - bash
    state: present
  become: yes

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/bash/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - .bashrc
