- name: make sure packages are installed
  package:
    name:
      - hyprland
      - thunar
      - ttf-font-awesome
      - waybar
      - swaync
      - hyprlock
      - hypridle
      - hyprpicker
      - pavucontrol
      - nm-connection-editor
    state: present
  become: yes


- name: make sure theme dependencies are installed
  package:
    name:
      - nwg-look
      - sassc
      - gnome-themes-extra
      - gtk-engine-murrine
    state: present
  become: yes

- name: Install theme via AUR.. this will take like 10m and you will think it is stuck
  kewlfft.aur.aur:
    name: hyprshot
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Install hyprshot via AUR
  kewlfft.aur.aur:
    name: hyprshot
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

# nwg-look installed above can also be used to set these
- name: Set theme in dconf
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Tokyonight-Light'"
    state: present

- name: Set themeicons in dconf
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Tokyonight-Light'"
    state: present

# https://github.com/Alexays/Waybar
# https://github.com/Alexays/Waybar/wiki
- name: create waybar config directory
  file:
    path: ~/.config/waybar
    state: directory

- name: symlink config files for waybar
  file:
    src: "{{ ansible_env.PWD }}/roles/hyprland/files/waybar/{{ item }}"
    path: "~/.config/waybar/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - config.jsonc
    - mocha.css
    - style.css

- name: create hyprland config directory
  file:
    path: ~/.config/hypr
    state: directory

- name: symlink config files for hyprland
  file:
    src: "{{ ansible_env.PWD }}/roles/hyprland/files/{{ item }}"
    path: "~/.config/hypr/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - hyprland.conf
    - hyprlock.conf
    - hypridle.conf
