- name: make sure hyprland is installed
  package:
    name:
      - hyprland
    state: present
  become: yes

- name: make sure dolphin is installed
  package:
    name:
      - dolphin
    state: present
  become: yes

- name: make sure wofi is installed
  package:
    name:
      - wofi
    state: present
  become: yes


- name: make sure ttf-font-awesome is installed so waybar can render
  package:
    name:
      - ttf-font-awesome
    state: present
  become: yes

- name: make sure waybar is installed
  package:
    name:
      - waybar
    state: present
  become: yes

# https://github.com/Alexays/Waybar
# https://github.com/Alexays/Waybar/wiki
- name: create waybar config directory
  file:
    path: ~/.config/waybar
    state: directory

- name: symlink config files for waybar
  file:
    src: "{{ ansible_env.PWD }}/roles/hyprland/files/waybar/{{ item }}"
    path: "~/.config/waybar/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - config.jsonc

- name: create hyprland config directory
  file:
    path: ~/.config/hypr
    state: directory


- name: symlink config files for hyprland
  file:
    src: "{{ ansible_env.PWD }}/roles/hyprland/files/{{ item }}"
    path: "~/.config/hypr/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - hyprland.conf
