# nwg-look installed above can also be used to set these (GTK settings application)

# https://github.com/Fausto-Korpsvart/Tokyonight-GTK-Theme
- name: make sure theme dependencies are installed
  package:
    name:
      - nwg-look
      - sassc
      - gnome-themes-extra
      - gtk-engine-murrine
    state: present
  become: yes

- name: Install theme via AUR.. this will take like 10m and you will think it is stuck
  kewlfft.aur.aur:
    name: tokyonight-gtk-theme-git
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Set gtk theme for gnome widgets in dconf
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Tokyonight-Dark'"
    state: present

- name: Set themeicons for gnome widget in dconf
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Tokyonight-Dark'"
    state: present

- name: Set prefer dark for gnome widget in dconf
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
- include_tasks: "gtk3.yml"
- include_tasks: "gtk4.yml"

