
# https://github.com/LGFae/swww
# Animated backgrounds
# \
- name: make sure packages are installed
  package:
    name:
      - swww
    state: present
  become: yes

- name: create backgrounds config directory
  file:
    path: ~/.config/backgrounds
    state: directory

- name: symlink config files for backgrounds
  file:
    src: "{{ ansible_env.PWD }}/roles/swww/files/{{ item }}"
    path: "~/.config/backgrounds/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - 2077.gif
