
# https://formulae.brew.sh/formula/synergy-core


- name: make sure packages are installed
  community.general.homebrew:
    name:
      - synergy-core
    state: present

# Synergy requires the 'Accessibility' permission.
# You can grant this permission by navigating to:
#     System Preferences -> Security & Privacy -> Privacy -> Accessibility

# If Synergy still doesn't work, try clearing the 'Accessibility' list:
#     sudo tccutil reset Accessibility
# You can then grant the 'Accessibility' permission again.
# You may need to clear this list each time you upgrade synergy-core.

# On ARM macOS machines, the 'Accessibility' permission must be granted to
# both of the following two items:
#     (1) $HOMEBREW_PREFIX/opt/synergy-core/bundle/Synergy.app
#     (2) $HOMEBREW_PREFIX/opt/synergy-core/bin/synergy
