
# https://symless.com/synergy/download/package/mac/synergy-3.2.1-macos-x64.dmg
# https://symless.com/synergy/download/package/mac/synergy-3.2.1-macos-arm64.dmg
# https://symless.com/synergy/download

    - name: Download Synergy DMG file
      get_url:
        url: "https://symless.com/synergy/download/package/mac/synergy-3.2.1-macos-x64.dmg"
        dest: "/tmp/synergy.dmg"
        checksum: "sha256:8b7a4b02b728c2f2918f18f24d878427b2be3d83b027785e838888487d8d9b04"

    - name: Mount Synergy DMG
      command: hdiutil mount "/tmp/synergy.dmg"

    - name: Install Synergy application
      command: /Volumes/Synergy/Synergy.app/Contents/MacOS/Synergy 
        args: 
          - --agree-to-license
          - --no-restart
        # Adjust the above command and args based on the actual installation command 

    - name: Unmount Synergy DMG
      command: hdiutil unmount "/tmp/synergy.dmg" 

    - name: Cleanup Synergy DMG
      file:
        path: "/tmp/synergy.dmg"
        state: absent
