- name: make sure jre-openjdk-headless is installed
  package:
    name:
      - jre-openjdk-headless
    state: present
  become: "yes"

- name: Add minecraft user
  ansible.builtin.user:
    name: minecraft
    shell: /bin/nologin
    home: /opt/minecraft
    create_home: true
    password_lock: true
  become: yes

- name: Create directories
  ansible.builtin.file:
    path: /opt/minecraft/{{item}}
    state: directory
    owner: minecraft
    group: minecraft
    mode: '0755'
  loop:
    - server
  become: yes
    
- name: Download server.jar
  ansible.builtin.get_url: 
    url: "https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar"
    dest: /tmp/minecraft-server.jar
    checksum: "sha512:f8a1c1b6f2ca9f6960e71abddbd994930d710a75711e9ea3b6f148ffa5cc0d94350d728379a5811f7796c9825b846f578d01bdc0f5f421ae13abdcfd504ff366"

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/minecraft/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - minecraft.service

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/minecraft/files/minecraft.service"
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: copy server.jar
  ansible.builtin.copy:
    src: "/tmp/minecraft-server.jar"
    dest: /opt/minecraft/server/server.jar
    owner: root
    group: root
    mode: 0644
  become: yes

# If you dont do this you need to start the service and do systemctl daemon-reload
# - name: Start and enable user service for minecraft
#   ansible.builtin.systemd_service:
#     name: minecraft
#     state: started
#     daemon_reload: true
#     enabled: true

# After you do this you need to accept the eula in eula.txt copy the backup into the /opt/minecraft/server directory, set the level name to match it and adjust the port in the server properties file after the first boot

