
- name: make sure kitty is installed
  package:
    name:
      - kitty
    state: present
  become: "{{yes if ansible_os_family == 'linux' else 'no'}}"

- name: create kitty config directory
  file:
    path: ~/.config/kitty
    state: directory

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/kitty/files/{{ item }}"
    path: "~/.config/kitty/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - kitty.conf
    - themes
