#!/usr/bin/env bash

if [[ $# -eq 0 ]] ; then
    echo 'pass a session name eg: $0 session_name';
    exit 1
fi

tmux new-session -t $1 \; \
  split-window -v -p 20 \; \
  select-pane -t 0 \; \
  send-keys 'vim .' C-m \; \



