
- name: symlink gitconfig files work
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/.gitconfig-work"
    path: "~/.gitconfig"
    state: link
    follow: false
    force: yes
  loop:
    - .gitconfig
