
- name: make sure git is installed
  package:
    name:
      - git
    state: present
  become: "{{'yes' if ansible_os_family == 'Archlinux' else 'no'}}"

- name: symlink gitconfig files
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/.gitconfig"
    path: "~/.gitconfig"
    state: link
    follow: false
    force: yes
  loop:
    - .gitconfig
