- name: make sure emacs is installed
  package:
    name:
      - emacs

    state: present
  become: "yes"

- name: make sure fonts are installed
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-ubuntu-font-family
    state: present
  become: "yes"

- name: make sure libraries are installed
  package:
    name:
      - cmake

      - pyright

      # required to build vterm-module
      - make
      - libvterm
    state: present
  become: "yes"

- name: Start and enable user service for emacs
  ansible.builtin.systemd_service:
    name: emacs
    state: started
    enabled: true
    scope: user

- name: Override the provided .desktop files with ones that will call clientwrapper script
  file:
    src: "{{ ansible_env.PWD }}/roles/emacs/files/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - emacs.desktop
    - emacsclient.desktop
