- name: Install emacs as an application
  community.general.homebrew_cask:
    name:
      - emacs
    state: present

- name: make sure packages are installed
  community.general.homebrew:
    name:
      - pyright
    state: present

- name: Unset preference that keeps titlebar in light mode
  ansible.builtin.shell:
    cmd: defaults write org.gnu.Emacs NSRequiresAquaSystemAppearance -bool no

# https://jherrlin.github.io/posts/emacs-on-macos-monterey/
- name: Deploy custom emacs job definition
  template:
    src: files/gnu.emacs.plist.j2
    dest: "/Library/LaunchDaemons/gnu.emacs.plist"
    owner: "root"
    group: "wheel"
    mode: "0644"
  become: yes

- name: Run emacs
  community.general.launchd:
    name: gnu.emacs
    state: started
    enabled: true
  become: yes

# Then you need to create an automator script named Emacs Client in the applications folder that runs a bash script like(dont overwrite Emacs as you wont be able to execute the emacsclient binary if you do), replace its icon by doing get info and dragging the emacs icon over the automator one (the small one at the top left and not the big preview one), drag this onto your quickbar afterwards
# export PATH=/usr/local/bin:$PATH
# emacsclientw > /dev/null 2>&1 &



