- name: Install emacs as an application
  community.general.homebrew_cask:
    name:
      - emacs
    state: present

- name: make sure packages are installed
  community.general.homebrew:
    name:
      - pyright
    state: present

- name: Unset preference that keeps titlebar in light mode
  ansible.builtin.shell:
    cmd: defaults write org.gnu.Emacs NSRequiresAquaSystemAppearance -bool no

# https://jherrlin.github.io/posts/emacs-on-macos-monterey/
- name: Deploy custom emacs job definition
  template:
    src: files/gnu.emacs.plist.j2
    dest: "/Library/LaunchDaemons/gnu.emacs.plist"
    owner: "root"
    group: "wheel"
    mode: "0644"
  become: yes

- name: Run emacs
  community.general.launchd:
    name: gnu.emacs
    state: started
    enabled: true


# Then put this in an automator script and put it in the applications folder...
#emacsclient -nc

