- name: Install emacs as an application
  community.general.homebrew_cask:
    name:
      - emacs
    state: present

- name: make sure packages are installed
  community.general.homebrew:
    name:
      - pyright
    state: present

- name: Unset preference that keeps titlebar in light mode
  ansible.builtin.shell:
    cmd: defaults write org.gnu.Emacs NSRequiresAquaSystemAppearance -bool no

