- include_tasks: "{{ ansible_os_family }}.yml"
- name: create emacs config directory
  file:
    path: ~/.config/emacs
    state: directory

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/emacs/files/{{ item }}"
    path: "~/.config/emacs/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - alarm.wav
    - config.org
    - early-init.el
    - images
    - init.el
    - scripts

- name: symlink emacsclientw script
  file:
    src: "{{ ansible_env.PWD }}/roles/emacs/files/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
    state: link
    follow: false
    force: yes
  become: yes
  loop:
    - emacsclientw
