

- name: make sure emacs is installed
  package:
    name:
      - emacs

    state: present
  become: "{{'yes' if ansible_os_family == 'Archlinux' else 'no'}}"


- name: make sure fonts are installed
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-ubuntu-font-family
    state: present
  become: "{{'yes' if ansible_os_family == 'Archlinux' else 'no'}}"


- name: make sure libraries are installed
  package:
    name:
      - cmake
      - make
      - libvterm
    state: present
  become: "{{'yes' if ansible_os_family == 'Archlinux' else 'no'}}"

- name: create emacs config directory
  file:
    path: ~/.config/emacs
    state: directory

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/emacs/files/{{ item }}"
    path: "~/.config/emacs/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - alarm.wav
    - config.org
    - early-init.el
    - images
    - init.el
    - scripts
