
- name: make sure packages are installed
  package:
    name:
      - wofi
    state: present
  become: yes

- name: create wofi config directory
  file:
    path: ~/.config/wofi
    state: directory

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/wofi/files/{{ item }}"
    path: "~/.config/wofi/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - launch.sh
    - link_flatpak_steam_games.sh
    - style.css
    - config
