- name: make sure starship is installed
  package:
    name:
      - starship
    state: present
  become: "{{yes if ansible_os_family == 'linux' else 'no'}}"

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/starship/files/{{ item }}"
    path: "~/.config/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - starship.toml
